[package]
name = "opus_cli"
version = "0.1.0-alpha"
edition = "2021"

[dependencies]
chrono = "0.4.22"
rusqlite = { version = "0.28.0", features = ["bundled"] }
serde_json = "1.0"
serde = { version = "1.0.145", features = ["derive"] }
